
room:
  length: 10
  width: 5
  height: 3

table:
  length: 5
  width: 2
  height: 1.2
  offset_from_wall:
    left: 1.8
    front: 2

speaker:
  position: [4.3, 3, 1.2]

microphones:
  positions:
    - [4.3, 3, 1.2]
